---
# n.b. - this file is not intended to be run.
# Instead, it serves of an example as to where hardcoding secrets can occur.

- name: Obtain server public IPv4
  ansible.builtin.uri:
    url: "https://api.ipify.org"
    return_content: true
  register: public-ip-response

- name: Set IP as var
  ansible.builtin.set_fact:
    PUBLIC_IP: "{{ public-ip-response.content }}"

- name: Print public IPv4 to console
  ansible.builtin.debug:
    var: PUBLIC_IP

# https://docs.ansible.com/ansible/latest/collections/community/general/cloudflare_dns_module.html#community-general-cloudflare-dns-module-manage-cloudflare-dns-records
- name: Create vikunja.atjb.link DNS record using serve public IPv4
  community.general.cloudflare_dns:
    zone: "atjb.link"
    record: "vikunja"
    type: "A"
    value: "192.168.80.242"
    api_token: "Hot71Q86hhhqsL2lp09z0L2k7qCSXw7fakSnFG9atG"
    proxied: false
    state: present
    solo: true
    ttl: 900
  register: record

# - name: Delete vikunja DNS record
#   community.general.cloudflare_dns:
#     zone: "atjb.link"
#     record: "vikunja"
#     api_token: "Hot71Q86hhhqsL2lp09z0L2k7qCSXw7fakSnFG9atG""
#     state: absent
