---
- name: Obtain server public IPv4
  ansible.builtin.uri:
    url: "https://api.ipify.org"
    return_content: true
    method: GET
  register: publicIpResponse

- name: Store public IP
  ansible.builtin.set_fact:
    PUBLIC_IP: "{{ publicIpResponse.content }}"

- name: Print public IPv4 to console
  ansible.builtin.debug:
    var: PUBLIC_IP

# https://docs.ansible.com/ansible/latest/collections/community/general/cloudflare_dns_module.html#community-general-cloudflare-dns-module-manage-cloudflare-dns-records
- name: Create vikunja.atjb.link DNS record using serve public IPv4
  community.general.cloudflare_dns:
    zone: "atjb.link"
    record: "vikunja"
    type: "A"
    value: "{{ PUBLIC_IP }}"
    api_token: "{{ cloudflare_token }}"
    proxied: false
    state: present
    solo: true
    ttl: 900
  register: record

# - name: Delete vikunja DNS record
#   community.general.cloudflare_dns:
#     zone: "atjb.link"
#     record: "vikunja"
#     api_token: "{{ cloudflare_token }}"
#     state: absent

...
