---
- name: Obtain public IPv4
  ansible.builtin.uri:
    url: "https://api.ipify.org"
    return_content: yes
  register: public_ip_response

- set_fact:
    PUBLIC_IP: "{{ public_ip_response.content }}"

- name: Print public IPv4 to console
  debug:
    var: PUBLIC_IP

# - name: Print bitwarden lookup values
#   debug:
#     var: "{{ cloudflare_zone }}"

# - name: Print bitwarden lookup values
#   debug:
#     var: "{{ cloudflare_record }}"

# - name: Print bitwarden lookup values
#   debug:
#     var: "{{ cloudflare_email }}"

# - name: Print bitwarden lookup values
#   debug:
#     var: "{{ cloudflare_token }}"

# - name: Set Cloudflare DNS A record
#   community.general.cloudflare_dns:
#     zone: "130336886d4ca2c308af1bcc99e1536e"
#     record: "testtest"
#     type: "A"
#     value: "{{ PUBLIC_IP }}"
#     account_email: "atjbramley@hotmail.com"
#     account_api_key: "{{ cloudflare_token }}"
#   register: record

- name: Create a test.example.net A record to point to 127.0.0.1
  community.general.cloudflare_dns:
    zone: atjb.link
    record: testityyy
    type: A
    value: 127.0.0.1
    proxied: false
    account_email: atjbramley@hotmail.com
    account_api_token: "{{ cloudflare_token }}"
    state: present
  register: record

...
