---
- name: Run subtasks
  hosts: "{{ deployment_env }}"
  vars_files:
    - ./vars/global.yml
    - ./vars/{{ deployment_env }}.yml
    - ./global/vars/global_vars.yml
    - ./certbot/vars/certbot_vars.yml
    - ./create-ansible-user/vars/create_ansible_user_vars.yml
    - ./cloudflare/vars/cloudflare_vars.yml
  roles:
    - docker
    - cloudflare
    - certbot
    - nginx
    - vikunja
    - debug
...
