---
- name: Run subtasks
  hosts: "{{ deployment_env }}"
  vars_files:
    - ./vars/global.yml
    - ./vars/{{ deployment_env }}.yml
    - ./cloudflare/vars/cloudflare_vars.yml
  roles:
    - docker
    - cloudflare
    - certbot
    - nginx
    - vikunja
    # debug
...
