---
- name: Install Nginx
  ansible.builtin.apt:
    name: nginx
    state: present

- name: Copy nginx config file
  ansible.builtin.copy:
    src: ./files/nginx.conf
    dest: /etc/nginx/
    owner: root
    group: root
    mode: '0644'

- name: Configure vikunja nginx config
  ansible.builtin.template:
    src: ./files/vikunja.conf.j2
    dest: /etc/nginx/sites-available/vikunja.conf
    owner: root
    group: root
    mode: '0644'

- name: Symlink to enable vikunja
  ansible.builtin.file:
    src: /etc/nginx/sites-available/vikunja.conf
    dest: /etc/nginx/sites-enabled/vikunja.conf
    state: link
  notify: Reload nginx

...
