---
version: "3"

services:
  db:
    container_name: vikunja_db
    image: mariadb:10
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_USER: vikunja
      MYSQL_DATABASE: vikunja
    volumes:
      - ./db:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h localhost -u $$MYSQL_USER --password=$$MYSQL_PASSWORD",
        ]
      interval: 2s
      start_period: 30s

  vikunja:
    container_name: vikunja
    image: vikunja/vikunja
    environment:
      VIKUNJA_SERVICE_ROOTPATH: /app/vikunja/config.yml:ro

    ports:
      - 3456:3456
    volumes:
      - ./files:/app/vikunja/files
      - ./config/config.yml:/app/vikunja/config.yml:ro
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
...
