---
- name: Setup
  block:
    - name: Create config directory
      ansible.builtin.file:
        path: /opt/vikunja/config
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: Copy bootstrap files
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: "0777"
      loop:
        - { src: "../files/config.yml", dest: "/opt/vikunja/config/config.yml" }
        - { src: "../files/docker-compose.yml", dest: "/opt/vikunja/docker-compose.yml" }

- name: Prepare config.yml
  block:
    - name: Set DB password dynamically from BWS
      ansible.builtin.set_fact:
        vikunja_db_password: "{{ lookup('bitwarden.secrets.lookup', vars[deployment_env]['vikunja']['vikunja_db_password']) }}"

    - name: Inject DB password into config.yml
      ansible.builtin.lineinfile:
        path: /opt/vikunja/config/config.yml
        insertafter: "^database:$"
        line: "  password: {{ vikunja_db_password }}"

    - name: Set SMTP details dynamically from BWS
      ansible.builtin.set_fact:
        smtp_dict: >-
          {{
            smtp_dict | default({}) |
            combine ({ item.key: lookup('bitwarden.secrets.lookup', item.value )})
          }}
      loop:
        - { key: 'smtp_host', value: "{{ vars[deployment_env]['smtp']['smtp_host'] }}" }
        - { key: 'smtp_username', value: "{{ vars[deployment_env]['smtp']['smtp_username'] }}" }
        - { key: 'smtp_password', value: "{{ vars[deployment_env]['smtp']['smtp_password'] }}" }
        - { key: 'smtp_from_address', value: "{{ vars[deployment_env]['smtp']['smtp_from_address'] }}" }

    - name: Inject SMTP details into config.yml
      ansible.builtin.blockinfile:
        path: /opt/vikunja/config/config.yml
        insertafter: "^mailer:$"
        block: |
          {% filter indent(width=2, first=true) %}
          host: {{ smtp_dict.smtp_host }}
          username: {{ smtp_dict.smtp_username }}
          password: {{ smtp_dict.smtp_password }}
          fromemail: {{ smtp_dict.smtp_from_address }}
          {% endfilter %}
        marker: "# {mark} BITWARDEN SECRETS MANAGER MANAGED BLOCK"

    - name: Inject FQDN into config.yml
      ansible.builtin.lineinfile:
        path: /opt/vikunja/config/config.yml
        insertafter: "^service:$"
        line: "  frontendurl: https://{{ vars[deployment_env]['dns']['subdomain'] }}.{{ vars[deployment_env]['dns']['domain'] }}"
        create: true

- name: Prepare docker-compose.yml
  block:
    - name: Set DB passwords dynamically from BWS
      ansible.builtin.set_fact:
        "{{ item.key }}": "{{ lookup('bitwarden.secrets.lookup', item.secret_id) }}"
      loop:
        - { key: 'root_db_password', secret_id: "{{ vars[deployment_env]['vikunja']['root_db_password'] }}" }
        - { key: 'vikunja_db_password', secret_id: "{{ vars[deployment_env]['vikunja']['vikunja_db_password'] }}" }

    - name: Inject secrets into docker-compose.yml
      ansible.builtin.lineinfile:
        path: /opt/vikunja/docker-compose.yml
        insertafter: "{{ item.insertafter }}"
        line: "{{ item.line }}"
      loop:
        - { insertafter: "MYSQL_DATABASE:", line: "            MYSQL_ROOT_PASSWORD: {{ root_db_password }}" }
        - { insertafter: "MYSQL_USER:", line: "            MYSQL_PASSWORD: {{ vikunja_db_password }}" }

- name: Run Vikunja
  block:
    - name: Run Vikuna
      community.docker.docker_compose_v2:
        project_src: /opt/vikunja
        state: present
        pull: always
        recreate: always

...
