---
# Vikunja Configuration
# https://vikunja.io/docs/config-options/
# 2 spaces => tabs

service:
  frontendurl: "157.245.208.55"
  maxitemsperpage: 50
  enablecaldav: true
  motd: "Demo Vikunja Server that was produced with the help of Bitwarden Secrets Manager"
  enablelinksharing: true
  enableregistration: true
  enabletaskattachments: true
  timezone: "CET"
  enabletaskcomments: true
  enabletotp: true
  enableemailreminders: true
  maxavatarsize: 1024

database:
  host: "db"
  type: "mysql"
  database: "vikunja-db"
  user: "vikunja"

cache:
  enabled: false

redis:
  enabled: false

cors:
  enabled: false

mailer:
  enabled: true
  port: 587
  authtype: "plain"
  skiptlsverify: false
  queuelength: 100
  queuetimeout: 30
  forcessl: false

log:
  enabled: true
  path:
  standard: "stdout"
  level: "INFO"
  database: "off"
  databaselevel: "WARNING"
  http: "stdout"
  echo: "off"
  events: "stdout"
  eventslevel: "info"

ratelimit:
  enabled: true
  kind: user
  period: 60
  limit: 100
  store: memory

files:
  basepath: ./files
  maxsize: 100MB

migration:
  wunderlist:
    enable: false
  todoist:
    enable: false
  trello:
    enable: false
  microsofttodo:
    enable: false

avatar:
  gravatarexpiration: 3600

backgrounds:
  enabled: true
  providers:
    upload:
      enabled: true
    unsplash:
      enabled: false

legal:

keyvalue:
  type: "memory"

auth:
  local:
    enabled: true
  openid:
    enabled: false

metrics:
  enabled: true
  username:
  password:
...